from __future__ import annotations

from pathlib import Path

import typer

app = typer.Typer(help="NervLynx developer scaffolding CLI.")


def _write(path: Path, content: str) -> None:
  path.parent.mkdir(parents=True, exist_ok=True)
  path.write_text(content, encoding="utf-8")


@app.command("init")
def init_project(
  project_name: str = typer.Argument(..., help="Plugin-pack project directory name."),
  output_dir: Path = typer.Option(Path("."), help="Parent directory where scaffold is created."),
  force: bool = typer.Option(False, "--force", help="Overwrite files if target already exists."),
) -> None:
  """Scaffold a starter NervLynx plugin-pack project."""
  pkg = project_name.replace("-", "_")
  root = output_dir / project_name
  if root.exists() and any(root.iterdir()) and not force:
    typer.echo(f"target directory is not empty: {root}. Use --force to overwrite.")
    raise typer.Exit(code=1)

  _write(
    root / "README.md",
    f"""# {project_name}

Starter NervLynx plugin pack generated by `nervlynx init`.

## Install

```bash
pip install -e .
```

## Validate

```bash
pytest -q
robot-core plugin-catalog
```
""",
  )

  _write(
    root / "pyproject.toml",
    f"""[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "{project_name}"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = ["nervlynx"]

[project.optional-dependencies]
dev = ["pytest>=8.0.0"]

[project.entry-points."nervlynx.sensors"]
{pkg}_camera_sensor = "{pkg}.plugins:CameraIngestSensorPlugin"

[project.entry-points."nervlynx.nodes"]
{pkg}_planner = "{pkg}.plugins:PlannerStubNodePlugin"
{pkg}_actuator = "{pkg}.plugins:ActuatorMockNodePlugin"

[tool.setuptools]
package-dir = {{"": "."}}

[tool.setuptools.packages.find]
where = ["."]
include = ["{pkg}*"]
""",
  )

  _write(root / pkg / "__init__.py", "__all__ = []\n")

  _write(
    root / pkg / "plugins.py",
    """from __future__ import annotations

from dataclasses import dataclass

from robot_core.plugins import NodePlugin, SensorPlugin
from robot_core.runtime import RuntimeMessage


@dataclass(frozen=True)
class CameraIngestSensorPlugin(SensorPlugin):
  name: str = "starter_camera_sensor"

  def read(self) -> dict[str, object]:
    return {"camera_count": 2, "gps_fix": True, "imu_ok": True, "ai_ok": True}


@dataclass(frozen=True)
class PlannerStubNodePlugin(NodePlugin):
  name: str = "starter_planner"
  input_topics: list[str] = None  # type: ignore[assignment]

  def __post_init__(self) -> None:
    object.__setattr__(self, "input_topics", ["perception.scene"])

  def handle(self, msg: RuntimeMessage) -> list[tuple[str, str, dict[str, object]]]:
    confidence = float(msg.payload.get("confidence", 0.0))
    mode = "go" if confidence >= 0.7 else "safe_slow"
    return [("mission.command", "MissionCommand", {"mode": mode, "confidence": confidence})]


@dataclass(frozen=True)
class ActuatorMockNodePlugin(NodePlugin):
  name: str = "starter_actuator"
  input_topics: list[str] = None  # type: ignore[assignment]

  def __post_init__(self) -> None:
    object.__setattr__(self, "input_topics", ["mission.command"])

  def handle(self, msg: RuntimeMessage) -> list[tuple[str, str, dict[str, object]]]:
    return [("actuator.feedback", "ActuatorFeedback", {"ok": True, "mode": msg.payload.get("mode", "unknown")})]
""",
  )

  _write(
    root / "config" / "graph.yaml",
    f"""name: {project_name}_graph
seed_topic: sensors.bundle
seed_schema: SensorBundle
seed_payload:
  camera_count: 4
  gps_fix: true
  imu_ok: true
  ai_ok: true
nodes:
  - plugin: {pkg}_planner
    input_topics: ["perception.scene"]
  - plugin: {pkg}_actuator
    input_topics: ["mission.command"]
""",
  )

  _write(
    root / "tests" / "test_plugins.py",
    f"""from {pkg}.plugins import ActuatorMockNodePlugin, CameraIngestSensorPlugin, PlannerStubNodePlugin
from robot_core.runtime import Envelope, RuntimeMessage


def test_sensor_returns_normalized_bundle() -> None:
  payload = CameraIngestSensorPlugin().read()
  assert "camera_count" in payload
  assert "gps_fix" in payload


def test_nodes_produce_expected_topics() -> None:
  planner = PlannerStubNodePlugin()
  actuator = ActuatorMockNodePlugin()
  msg = RuntimeMessage(
    envelope=Envelope(
      topic="perception.scene",
      source="perception",
      sequence=1,
      monotonic_time_ns=1,
      trace_id="starter",
      schema="SceneState",
    ),
    payload={{"confidence": 0.9}},
  )
  command = planner.handle(msg)[0]
  assert command[0] == "mission.command"
  feedback_input = RuntimeMessage(
    envelope=Envelope(
      topic="mission.command",
      source="planner",
      sequence=1,
      monotonic_time_ns=2,
      trace_id="starter",
      schema="MissionCommand",
    ),
    payload=command[2],
  )
  assert actuator.handle(feedback_input)[0][0] == "actuator.feedback"
""",
  )

  typer.echo(f"scaffold_created path={root}")


@app.command("version")
def version() -> None:
  """Print nervlynx CLI version."""
  typer.echo("nervlynx-cli 0.1")


if __name__ == "__main__":
  app()
